#!/usr/bin/env bash
warn()	{ echo "$@" >&2;	}
die()	{ warn "$@"; exit 1;	}

main() {
	local addr='USER@DOMAIN.TLD'
	local path='PATH/TO/PROJECT'
	local v="${1:-$(< VERSION)}"
	list_versions | grep -q -x -F "$v"      || die "Version '$v' is not released yet"

	rsync -avzR --size-only $(git ls-files .release/) "${addr}:${path}" &&
	ssh -o RequestTTY=yes "$addr" bash -l -c \' "set -x; cd '$path' && narada-install '$v'" \'
}

list_versions() {
	grep '^VERSION' migrate | sed 's/^VERSION\s\+\(\S\+\)\s*$/\1/'
}


main "$@"
