Narada base
===========

This repo contains base files used to initialize new
https://github.com/powerman/Narada[Narada] projects.

There are different sets of files available in different branches:

master:: base files suitable for most projects

socklog:: base files plus
https://github.com/powerman/narada-plugin-runit[runit] and
https://github.com/powerman/narada-plugin-socklog[socklog] plugins

doc:: (this branch) doesn't contain base files for narada, only
documentation about this repo


== Install

This is default repository for Narada, so you can create new Narada
project using one of these commands:

[source,sh]
narada-new [directory]
narada-new -b socklog [directory]


== Setup

=== ./build

You usually should edit it to set commands used to build and test your
project.

Default build implementation does nothing and suitable only for projects
which consists of simple scripts (for example, in Perl) while doesn't need
to be compiled or generated.

Also you may need to change commands used to run build-time tests if your
project doesn't use http://testanything.org/[TAP] tests in `t/**/*.t`
files.

=== ./release

You usually should edit it to set commands needed to release your project.

Default implementation release patch file with differences since previous
released version for all files in your project repo, except these:

----
.gitignore
build
release
deploy
migrate
----

This is suitable only for projects which should deploy their source code
(for example, projects implemented using Perl scripts).

=== ./deploy

You usually should edit it to set commands needed to deploy your project.

Default implementation will deploy your project into `_live/` subdirectory
and suitable only for local testing while development.

=== migrate

You usually shouldn't *modify* it, only *append* operations needed to migrate
(upgrade and downgrade) between current and next versions of your project.

But you usually should change some files created by these operations in
directory where you deployed your project - either manually on initial
deploy in different ways for different (devel, testing, production, etc.)
deploy locations, or automatically in same way for different deploy
directories by appending (or changing) migrate operations:

- `config/mysql/`: you may like to remove it if your project doesn't use
  MySQL
- `var/mysql/`: you may like to remove it if your project doesn't use
  MySQL
- `var/qmail/`: you may like to remove it if your project doesn't use
  `~/.qmail*` to handle incoming emails
- `config/crontab/backup`:
  * make sure default backup schedule (daily incremental backups, new
    full backup every week) is suitable for you or change it
  * replace `echo Reminder: ...` with real command used to (recommended)
    encrypt or compress and upload your backup somewhere, for example:
+
[source,sh]
----
narada-backup &&
rm -f var/backup/full.tar.gpg &&
gpg --s2k-count 1000000 --batch --cipher-algo AES256 -c \
    --passphrase-file config/backup/pass var/backup/full.tar &&
scp var/backup/full.tar.gpg USER@HOST:PATH/`date +"%Y%m%d-%H%M%S"`.full.gpg
----


== Usage


