narada-base
===========

This repo contains base files used to initialize new Narada projects.

There are different sets of files available in different branches:

master:: base files suitable for most projects

socklog:: base files plus runit and socklog plugins

doc:: (this branch) doesn't contain base files for narada, only
documentation about this repo

== Base files

=== ./build

You usually should edit it to add commands needed to build your project.

Default implementation does nothing and suitable only for projects which
consists of simple scripts (for example, in Perl) while doesn't need to be
compiled or generated.

Also you may need to change commands used to run build-time tests if your
project doesn't use http://testanything.org/[TAP] tests in `t/**/.t`
files.

=== ./release

You usually should edit it to add commands needed to release your project.

Default implementation release patch file with differences since previous
version for all files in your project repo, except these:

- `.gitignore`
- `build`
- `release`
- `deploy`
- `install.narada`

This is suitable only for project which should deploy it source code (for
example, if it implemented using Perl scripts).

=== ./deploy

You usually should edit it to add commands needed to release your project.

Default implementation will deploy your project into `_live/` subdirectory
and suitable only for local testing while development.

=== install.narada

You usually shouldn't edit it, only append operations needed to migrate
(upgrade and downgrade) between different versions of your project.

But you usually should change some files created by these operations in
directory where you deployed your project - either manually on initial
deploy in different ways for different (devel, testing, production, etc.)
deploy directories, or automatically in same way for different deploy
directories by appending (or changing) migrate operations:

- `config/mysql/`: you may remove it if your project doesn't use MySQL
- `var/mysql/`: you may remove it if your project doesn't use MySQL
- `var/qmail/`: you may remove it if your project doesn't use `~/.qmail*`
  to handle incoming emails
- `config/crontab/backup`:
  * make sure is default backup schedule (daily incremental backups, new
    full backup every week) is suitable for you or change it
  * replace `echo Reminder: ...` with real command used to (recommended)
    encrypt and upload your backup somewhere, for example:
+
[source,sh]
----
narada-backup &&
rm -f var/backup/full.tar.gpg &&
gpg --s2k-count 1000000 --batch --cipher-algo AES256 -c \
    --passphrase-file config/backup/pass var/backup/full.tar &&
scp var/backup/full.tar.gpg USER@HOST:PATH/`date +"%Y%m%d-%H%M%S"`.full.gpg
----


