Narada base
===========

This repo contains base files used to initialize new
https://github.com/powerman/Narada[Narada] projects.

There are different sets of files available in different branches:

master:: base files suitable for most projects

socklog:: base files plus
https://github.com/powerman/narada-plugin-runit[runit] and
https://github.com/powerman/narada-plugin-socklog[socklog] plugins,
for projects which needs to run background services (like fastcgi,
php-fpm, etc.) and able to use http://smarden.org/runit/[runit]

go:: base files suitable for Go projects

go-socklog:: merged branches go and socklog

doc:: (this branch) doesn't contain base files for Narada, only
documentation about this repo


== Install

This is default repository for Narada, so you can create new Narada
project using one of these commands:

[source,sh]
----
narada-new [directory]
narada-new -b socklog [directory]
----

It's also recommended to release new major/minor/patch version immediately
after creating new project and/or adding new complex plugins (like runit):

[source,sh]
----
./release --minor && ./deploy
----


== Upgrade from Narada 1.x

See https://github.com/powerman/narada-base/wiki#how-to-upgrade-narada-1x-project[wiki].


== Documentation

Documentation is in your project's directory, see
https://github.com/powerman/narada-base/blob/master/doc/narada-base.adoc[doc/narada-base.adoc].
